name: Production

on:
  push:
    branches:
      - master
jobs:
  core:
    uses: ./.github/workflows/core.yml
  publish-to-stores:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - run: echo "publishing to stores"
      
