name: Sandbox

on: pull_request

jobs:
  core:
    uses: ./.github/workflows/core.yml
  publish-to-beta-testers:
    needs: core
    runs-on: ubuntu-latest
    steps:
      - run: echo "publishing to beta testers..."
      
