name: Sandbox

on: pull_request

jobs:
  core:
    uses: ./.github/workflows/workflow-2.yml
  publish-to-beta-testers:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publishing to beta testers..."
      
